### ISSUE TITLE
ローディング画面の追加

### ISSUE THREAD

**Issue by Yusuke4869** [Undecided-Discord/Oshavery-Front#124]

**Comment by sayoi341** [comment]
### ディスコードの場合 
`/index`
`/app` (コントローラーぐるぐる)
-> `/channels/@me` 
-> `/channels/[guildID]/[channelID]`

### Oshaveryの場合（構想）
#### アカウントなし
`/index`
-> `/Loading` (Oshaveryアカウント有り無し確認 -> ないので作成 -> /users/meからユーザー情報を取得)
-> `/guild/[guildID[0]]/channel/[channelID[0]]`

#### アカウントあり
`/index`
-> `/Loading` (Oshaveryアカウント有り無し確認 -> あり -> /users/meからユーザー情報を取得)
-> `/guild/[guildID[0]]/channel/[channelID[0]]`

#### あり + 直接アクセス
`/guild/[guildID]/channel/[channelID]` (userContextなしなのでリダイレクト)
-> `/Loading` (cookie,Tokenから/users/meでユーザー情報を取得)
-> アクセスしてきたguildID・channelIDがある場合はもどる。ない場合は`/guild/[guildID[0]]/channel/[channelID[0]]`
