### ISSUE TITLE
README.mdの更新

### ISSUE THREAD

**Issue by YukiYuigishi** [Undecided-Discord/Oshavery-Front#191]

**Comment by YukiYuigishi** [comment]
追加する文言 
----------------------
## Special Thanks
@Nanai10a 
このプロジェクトに使用されているアイコンを作成していただきました。
publicディレクトリ内の画像の著作権は @Nanai10aに帰属します。

**Comment by Nanai10a** [comment]
> publicディレクトリ内の画像の著作権は @Nanai10aに帰属します。

どちらかと言うと, *Oshavery*(団体)が管理してくれれば良いと思う
ただ, 著作権は私が保有しているってだけ(？

*「Oshaveryのロゴです, 僕たちが保有してるよ. (作ったのはNanai10aです)」* みたいなイメージ

**Comment by YukiYuigishi** [comment]
了解
さて、どうやって書こうか
