### ISSUE TITLE
Oshavery logo License

### ISSUE THREAD

**Issue by YukiYuigishi** [Undecided-Discord/Oshavery-Front#203]
Oshaveryのlogoのライセンスについて

**Comment by Nanai10a** [comment]
- このロゴはOshaveryについて言及することにのみ使用できます
- これの使用についてOshaveryに明示的な許諾を取る必要はありません
  - 但し, 画像へ変更を加えることは一切認められません

---

"*Oshavery*団体での, 該当するassetsを使用したbranding" についての言及って感じに捉えていただければ.
また, 著作権はNanai10aが保有しています(放棄/譲渡はしていません)が, 基本的に*Oshavery*の管理下に置いてください.
あと, 何らかの形で私が制作したことを明記してください(目立つところである必要は無いです).
