### ISSUE TITLE
next.jsの導入

### ISSUE THREAD

**Issue by YukiYuigishi** [Undecided-Discord/Oshavery-Front#283]
@Yusuke4869 のNextjs-Templateを基にNext.jsを導入する
https://github.com/Yusuke4869/Nextjs-Template/tree/main

**Comment by Yusuke4869** [comment]
CSS Frameworkは使う？

**Comment by YukiYuigishi** [comment]
どうしようかもう少し意見を募るべきかな(私はCSSフレームワークわからん)

**Comment by YukiYuigishi** [comment]
とりあえずNextjs-Templateを基に動く環境を整えました。
CSS frameworkやstorybookを導入する際は新しくissueを立ててください
